#!/usr/bin/bash

cur_user=`whoami`
if [ ${cur_user} == "root" ]; then
    echo "Run as non-root user!!"
    exit 1
fi

# update bashrc
#sed -i '/.*alias.*/d' ~/.bashrc
#sed -i 's/\(.*PS1.*\)/#\1/' ~/.bashrc
cat >~/.bashrc<<EOF
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias dmesg='dmesg --color'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ll -a'

# https://stackoverflow.com/questions/16715103/bash-prompt-with-last-exit-code
__prompt_command() {
    local exitCode="$?"
    local RCol='\[\e[0m\]'
    local Red='\[\e[0;31m\]'
    local Gre='\[\e[0;32m\]'
    local BYel='\[\e[1;33m\]'
    local BBlu='\[\e[1;34m\]'
    local Pur='\[\e[0;35m\]'

    PS1="\t "
    [ ${exitCode} != 0 ] && PS1+="${Red}${exitCode} " || PS1+="${exitCode} "
    [ ${EUID} == 0 ] && PS1+="${Pur}\h " || PS1+="${Gre}\u@\h "
    PS1+="${BBlu}\w ${BYel}\\$ ${RCol}"
}
export PROMPT_COMMAND=__prompt_command
EOF
sudo cp -f ~/.bashrc /root

# some packages [archlinuxcn]
sudo pacman --noconfirm -S yay google-chrome visual-studio-code-bin
# sogou pinyin [archlinuxcn]
sudo pacman --noconfirm -S fcitx-configtool fcitx-qt5 fcitx-lilydjwg-git fcitx-sogoupinyin

# input method: other options
#fcitx [archlinux]; cannot change im by shift & need to ctrl+shift first
#(fcitx-im)= fcitx-qt5 fcitx fcitx-gtk2 fcitx-gtk3
#pacman -S fcitx-configtool fcitx-im
#fcitx [archlinuxcn]
#pacman -S fcitx-configtool fcitx-qt5 fcitx-lilydjwg-git

#input method config
cat >>~/.xprofile<<EOF
# input method
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
EOF

# config bing wallpaper
yay --noconfirm -S bing-wallpaper-git
sudo chmod 777 /var/cache/image-blur /usr/share/wallpapers/deepin
cat >>~/.xprofile<<EOF
# update wallpaper
bash ~/.wallpaper
EOF
cat >~/.wallpaper<<EOF
#!/usr/bin/bash
if [[ -s /home/${cur_user}/Pictures/Bing/desktop.jpg ]]; then
    picdate=`date +%Y%m%d -r/home/${cur_user}/Pictures/Bing/desktop.jpg`
    curdate=`date +%Y%m%d`
    if [ ${curdate} -le ${picdate} ]; then
        #echo "no need to update"
        exit 0
    fi
fi
rm -rf /home/${cur_user}/Pictures/Bing/*
bing-wallpaper
mv /home/${cur_user}/Pictures/Bing/* /home/${cur_user}/Pictures/Bing/desktop.jpg
rm -rf /var/cache/image-blur/*
cp -f /home/${cur_user}/Pictures/Bing/desktop.jpg /usr/share/wallpapers/deepin/desktop.jpg
gsettings set com.deepin.dde.appearance background-uris "['file:///usr/share/wallpapers/deepin/desktop.jpg', 'file:///usr/share/wallpapers/deepin/Sunset_of_the_Lake_Nam_by_Wang_Jinyu.jpg']"
EOF

# config git
#git config --global user.name ***
#git config --global user.email ***
#git config --global credential.helper store
#disable git fetch in vscode

# config ssh connections

# additional aur packages
yay --noconfirm -S ao p3x-onenote persepolis

rm -f /home/${cur_user}/arch*

# office
#pacman -S libreoffice-fresh-zh-cn

# gui firewall
#pacman -S gufw 

# gpu drivers
#(nvidia-utils, req by) nvidia lib32-nvidia-utils
#(dual gpu switch) optimus-manager-qt
# steam
#(steam, req by) steam-native-runtime
#(other req to properly start steam) ttf-liberation wqy-zenhei
# lutris
# https://superuser.com/questions/1276485/configure-ssh-key-path-to-use-for-a-specific-host
